# ========================================================
# 基础设置
# ========================================================
model = "resnet18"
dataset = "cifar10"

max_epochs = 10
batch_size = [8,16]
learning_rate = 1e-3
accelerator = "gpu"
task = "cls"

[transform]
style = "graph"

passes = [
    "runtime_analysis_ori",
    "tensorrt_int8",
    "sparsity_int8",
]

# ========================================================
# 1) 测试原始 PyTorch 模型 (baseline)
# ========================================================
[passes.runtime_analysis_ori]
type = "sparsity_int8"
num_batches = 1000            
num_GPU_warmup_batches = 10   
test = true              

# ========================================================
# 2) INT8 + 测速
# ========================================================
[passes.tensorrt_int8]
type = "tensorrt_int8"
by = "type"

num_calibration_batches = 10
post_calibration_analysis = true

    [passes.tensorrt_int8.default.config]
        quantize = true
        calibrators = ["percentile", "mse", "entropy"]
        percentiles = [99.0, 99.9, 99.99]
        precision = "int8"

    [passes.tensorrt_int8.fine_tune]
        fine_tune = true

    [passes.tensorrt_int8.default.input]
        calibrator = "histogram"
        quantize_axis = false

    [passes.tensorrt_int8.default.weight]
        calibrator = "histogram"
        quantize_axis = false

    [passes.tensorrt_int8.runtime_analysis]
        num_batches = 1000
        num_GPU_warmup_batches = 10
        test = true


# ========================================================
# 3) INT8 + 2:4稀疏 + 测速
# ========================================================
[passes.sparsity_int8]
type = "sparsity_int8"
by = "type"

num_calibration_batches = 10
post_calibration_analysis = true

    [passes.sparsity_int8.default.config]
        quantize = true
        calibrators = ["percentile", "mse", "entropy"]
        percentiles = [99.0, 99.9, 99.99]
        precision = "int8"

    [passes.sparsity_int8.fine_tune]
        fine_tune = true

    [passes.sparsity_int8.default.input]
        calibrator = "histogram"
        quantize_axis = false

    [passes.sparsity_int8.default.weight]
        calibrator = "histogram"
        quantize_axis = false

    [passes.sparsity_int8.runtime_analysis]
        num_batches = 1000
        num_GPU_warmup_batches = 10
        test = true
